(()=>{
 const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
 const modal=$('#modal'),cover=$('#cover'),finish=$('#finish'),toast=$('#toast'),timer=$('#timer'),timerPill=$('#timerPill'),count=$('#foundCount'),status=$('#status'),scroll=$('#sceneScroll'),map=$('#map'),image=$('#carImage');
 const DEFECTS={tire:['Изношенная шина','Износ протектора ухудшает сцепление и увеличивает тормозной путь.'],brake:['Повреждённый тормозной диск','Коррозия и борозды снижают эффективность торможения.'],shock:['Потёкший амортизатор','Масляные следы указывают на возможную потерю герметичности.'],exhaust:['Повреждённая выхлопная система','Коррозия и утечка газов вызывают шум и запах выхлопа.'],fluid:['Утечка жидкости','Пятно под машиной может быть маслом, антифризом или другой жидкостью.']};
 let found=new Set(),seconds=90,timerId=null,playing=false,hintIndex=0,audioCtx=null,pointerStart=null,imageReady=false;
 function setStatus(text,type=''){status.textContent=text;status.className='status'+(type?' '+type:'')}
 image.addEventListener('load',()=>{imageReady=true;setStatus('Фото загружено: '+image.naturalWidth+'×'+image.naturalHeight,'ok')});
 image.addEventListener('error',()=>{imageReady=false;setStatus('Ошибка загрузки изображения','warn')});
 if(window.GSA_AVIF){image.src='data:image/avif;base64,'+window.GSA_AVIF}else setStatus('Файл изображения не собран','warn');
 async function readyAudio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('no audio');if(!audioCtx)audioCtx=new AC();if(audioCtx.state==='suspended')await audioCtx.resume();return audioCtx}
 function tone(freq,dur,type,vol,delay=0){const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+dur+.04)}
 async function sound(kind){try{await readyAudio();if(kind==='correct'){tone(740,.13,'triangle',.28);tone(988,.14,'triangle',.30,.11);tone(1318,.18,'triangle',.25,.23);navigator.vibrate?.(45)}else if(kind==='wrong'){tone(230,.18,'square',.23);tone(155,.24,'sawtooth',.20,.09);navigator.vibrate?.([70,40,70])}else{tone(523,.10,'triangle',.23);tone(659,.10,'triangle',.23,.10);tone(784,.14,'triangle',.23,.20)}}catch{setStatus('Проверьте громкость мультимедиа','warn')}}
 function openGame(){modal.classList.add('on');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeGame(){modal.classList.remove('on');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';stopTimer();playing=false}
 $('#openMain').onclick=$('#badge').onclick=openGame;$('#close').onclick=closeGame;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeGame()});
 function fmt(s){return String(s/60|0).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}function updateTimer(){timer.textContent=fmt(seconds);timerPill.classList.toggle('low',seconds<=15)}function stopTimer(){if(timerId){clearInterval(timerId);timerId=null}}
 function showToast(a,b){$('#toastTitle').textContent=a;$('#toastText').textContent=b;toast.classList.add('on');clearTimeout(showToast.id);showToast.id=setTimeout(()=>toast.classList.remove('on'),2600)}
 function reset(){found.clear();count.textContent='0';$$('.ring').forEach(x=>x.classList.remove('on','hint'));$$('.wrong-mark').forEach(x=>x.remove());finish.style.display='none'}
 function start(){if(!imageReady){setStatus('Подождите загрузку фотографии','warn');return}stopTimer();reset();seconds=90;updateTimer();playing=true;cover.style.display='none';setStatus('Звук включён. Двигайте фото пальцем.','ok');scroll.scrollLeft=170;scroll.scrollTop=0;sound('start');timerId=setInterval(()=>{if(seconds>0){seconds--;updateTimer();if(!seconds){setStatus('Время вышло, поиск можно продолжить','warn');showToast('Время вышло','Можно продолжить поиск.')}}},1000)}
 $('#start').onclick=$('#againBtn').onclick=start;$('#soundBtn').onclick=()=>{sound('start');setStatus('Проверочный звук воспроизведён','ok')};
 function complete(){playing=false;stopTimer();setStatus('Все дефекты найдены','ok');setTimeout(()=>finish.style.display='grid',350)}function hit(id){if(!playing||found.has(id))return;found.add(id);document.querySelector('[data-r="'+id+'"]').classList.add('on');count.textContent=found.size;sound('correct');showToast(...DEFECTS[id]);if(found.size===5)complete()}
 $('#hintBtn').onclick=()=>{if(!playing)return;const left=Object.keys(DEFECTS).filter(x=>!found.has(x));if(!left.length)return;const id=left[hintIndex++%left.length],ring=document.querySelector('[data-r="'+id+'"]');ring.classList.add('hint');setTimeout(()=>ring.classList.remove('hint'),1700);showToast('Подсказка',DEFECTS[id][0])};
 function point(e){const p=map.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(map.getScreenCTM().inverse())}function wrong(x,y){const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.classList.add('wrong-mark');for(const d of [[-14,-14,14,14],[14,-14,-14,14]]){const l=document.createElementNS(ns,'line');l.classList.add('wrong-x');l.setAttribute('x1',x+d[0]);l.setAttribute('y1',y+d[1]);l.setAttribute('x2',x+d[2]);l.setAttribute('y2',y+d[3]);g.appendChild(l)}map.appendChild(g);setTimeout(()=>g.remove(),700)}
 map.addEventListener('pointerdown',e=>{if(playing)pointerStart={x:e.clientX,y:e.clientY,id:e.target.classList.contains('hot')?e.target.dataset.i:null}});map.addEventListener('pointercancel',()=>pointerStart=null);map.addEventListener('pointerup',e=>{if(!playing||!pointerStart)return;const dx=e.clientX-pointerStart.x,dy=e.clientY-pointerStart.y,id=pointerStart.id;pointerStart=null;if(Math.hypot(dx,dy)>14)return;if(id){hit(id);return}const p=point(e);wrong(p.x,p.y);sound('wrong');showToast('Мимо','Здесь всё в порядке. Посмотрите внимательнее.')});
 $$('.hot').forEach(el=>el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();hit(el.dataset.i)}}));$('#copyBtn').onclick=async e=>{try{await navigator.clipboard.writeText('GSA-300');e.target.textContent='Код скопирован'}catch{e.target.textContent='GSA-300'}};updateTimer();
})();